input {
  beats {
    port => 5044
  }
}

filter {

  csv {
    separator => ","
    columns => ["timestamp","server_ref","event","app_id","msisdn","channel","language","purpose_id","params","status","status_code","consent_status","consent"]
  }

  date {
    match => ["timestamp","yyyy-MM-dd HH:mm:ss"]
  }

}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "consent-logs"
  }
}
