input {
  beats {
    port => 5045
  }
}

filter {

  csv {
    separator => ","
    columns => ["timestamp","server_ref","event","app_id","msisdn","channel","language","purpose_id","param_ids","request_status","status_code","consent_status","user_input"]
  }

  date {
    match => ["timestamp","yyyy-MM-dd HH:mm:ss"]
  }

}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "consent-logs"
  }
}
